POST https://localhost:7080/api/v1/authentication/signup HTTP/1.1
Content-Type: application/json

{
  "username": "",
  "email": "",
  "password": "",
  "confirmPassword": "",
  "image": null
}

###

POST https://localhost:7080/api/v1/authentication/signin HTTP/1.1
Content-Type: application/json

{
  "email": "",
  "password": ""
}

###

POST  https://localhost:7080/api/v1/authentication/refresh-token HTTP/1.1
Content-Type: application/json

{
    "accessToken": "",
    "refreshToken": ""
}

###

POST  https://localhost:7080/api/v1/authentication/revoke HTTP/1.1
Content-Type: application/json
Authorization: Bearer 

###

POST  https://localhost:7080/api/v1/authentication/resend-confirmation-email HTTP/1.1
Content-Type: application/json

{
  "email": ""
}

###

POST  https://localhost:7080/api/v1/authentication/forgot-password HTTP/1.1
Content-Type: application/json

{
  "email": ""
}

###

POST  https://localhost:7080/api/v1/authentication/reset-password HTTP/1.1
Content-Type: application/json

{
  "email": "",
  "password": "",
  "confirmPassword": "",
  "code": ""
}

###

PUT https://localhost:7080/api/v1/authentication/change-password HTTP/1.1
Content-Type: application/json
Authorization: Bearer 

{
  "currentPassword": "",
  "newPassword": "",
  "confirmPassword": ""
}