@base_uri = https://localhost:7080

POST {{base_uri}}/api/v1/authentication/signup HTTP/1.1
Content-Type: application/json

{
  "username": "",
  "email": "",
  "password": "",
  "confirmPassword": "",
  "image": null
}

###

POST {{base_uri}}/api/v1/authentication/signin HTTP/1.1
Content-Type: application/json

{
  "email": "",
  "password": ""
}

###

POST  {{base_uri}}/api/v1/authentication/refresh-token HTTP/1.1
Content-Type: application/json

{
    "accessToken": "",
    "refreshToken": ""
}

###

POST  {{base_uri}}/api/v1/authentication/revoke HTTP/1.1
Content-Type: application/json
Authorization: Bearer 

###

POST  {{base_uri}}/api/v1/authentication/resend-confirmation-email HTTP/1.1
Content-Type: application/json

{
  "email": ""
}

###

POST  {{base_uri}}/api/v1/authentication/forgot-password HTTP/1.1
Content-Type: application/json

{
  "email": ""
}

###

POST  {{base_uri}}/api/v1/authentication/reset-password HTTP/1.1
Content-Type: application/json

{
  "email": "",
  "password": "",
  "confirmPassword": "",
  "code": ""
}

###

PUT {{base_uri}}/api/v1/authentication/change-password HTTP/1.1
Content-Type: application/json
Authorization: Bearer 

{
  "currentPassword": "",
  "newPassword": "",
  "confirmPassword": ""
}

###

GET {{base_uri}}/api/v1/authentication/generate-authenticator-key HTTP/1.1
Content-Type: application/json
Authorization: Bearer 