@base_uri = https://localhost:7080/api/v1
@access_token = {{signinRequest.response.body.data.accessToken}}

###
# @name signinRequest 
POST {{base_uri}}/authentication/signin HTTP/1.1
Content-Type: application/json

{
  "email": "",
  "password": ""
}

###

GET {{base_uri}}/transactions?pageSize=10&pageNumber=1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

###

POST {{base_uri}}/transactions HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "transactionDate": "",
  "description": "",
  "categoryId": "",
  "amount": 0.01,
  "comments": "", 
  "isExpense": false
}

###

GET {{base_uri}}/transactions/balance HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

###

@id = 

PUT {{base_uri}}/transactions/{{id}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "description": "",
  "categoryId": "",
  "amount": 0.01,
  "comments": "", 
}

###

GET {{base_uri}}/transactions/{{id}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

###

DELETE {{base_uri}}/transactions/{{id}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}