@base_uri = https://localhost:7080
@access_token = {{signinRequest.response.body.data.accessToken}}

###
# @name signinRequest 
POST {{base_uri}}/api/v1/authentication/signin HTTP/1.1
Content-Type: application/json

{
  "email": "",
  "password": ""
}

###

GET https://localhost:7080/api/v1/transaction-categories?pageSize=10&pageNumber=1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

###

POST https://localhost:7080/api/v1/transaction-categories HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "name": ""
}