@base_uri = https://localhost:7080/api/v1
@access_token = {{signinRequest.response.body.data.accessToken}}

###
# @name signinRequest 
POST {{base_uri}}/authentication/signin HTTP/1.1
Content-Type: application/json

{
  "email": "",
  "password": ""
}

###

PUT {{base_uri}}/user/image HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "image": ""
}

###

GET {{base_uri}}/user HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

###

GET {{base_uri}}/user/delete-token HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

###

@deleteToken = 

DELETE {{base_uri}}/user/{{deleteToken}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}
